air: 0
stone: 1
grass: 2
dirt: 3
cobblestone: 4
wood: 5
sapling: 6
bedrock: 7
water: 8
water_pool: 9
lava: 10
lava_pool: 11
sand: 12
gravel: 13
gold_ore: 14
iron_ore: 15
coal_ore: 16
log: 17
leaves: 18
sponge: 19
glass: 20
red_cloth: 21
orange_cloth: 22
yellow_cloth: 23
lime_cloth: 24
green_cloth: 25
aqua_cloth: 26
cyan_cloth: 27
blue_cloth: 28
purple_cloth: 29
indigo_cloth: 30
violet_cloth: 31
magenta_cloth: 32
pink_cloth: 33
black_cloth: 34
grey_cloth: 35
white_cloth: 36
yellow_flower: 37
red_rose: 38
brown_mushroom: 39
red_mushroom: 40
gold: 41
iron: 42
double_stair: 43
stair: 44
brick: 45
tnt: 46
bookcase: 47
mossy_cobblestone: 48
obsidian: 49
torch: 50
fire: 51
mob_spawner: 52
wood_stairs: 53
chest: 54
redstone_wire: 55
diamond: 56
diamond_block: 57
workbench: 58
crops: 59
soil: 60
furnace: 61
burning_furnace: 62
sign: 63
door: 64
ladder: 65
rail: 66
cobblestone_stairs: 67
sign: 68
lever: 69
stone_plate: 70
iron_door: 71
wood_plate: 72
redstone_ore: 73
lit_redstone_ore: 74
redstone_torch: 75
redstone_torch_on: 76
stone_button: 77
snow: 78
ice: 79
snow_block: 80
cactus: 81
clay: 82
reed: 83
jukebox: 84

