iron_shovel: 256
iron_pickaxe: 257
iron_axe: 258
flint_and_steel: 259
apple: 260
bow: 261
arrow: 262
coal: 263
diamond: 264
iron_ingot: 265
gold_ingot: 266
iron_sword: 267
wood_sword: 268
wood_shovel: 269
wood_pickaxe: 270
wood_axe: 271
stone_sword: 272
stone_shovel: 273
stone_pickaxe: 274
stone_axe: 275
diamond_sword: 276
diamond_shovel: 277
diamond_pickaxe: 278
diamond_axe: 279
stick: 280
bowl: 281
mushroom_soup: 282
gold_sword: 283
gold_shovel: 284
gold_pickaxe: 285
gold_axe: 286
string: 287
feather: 288
gunpowder: 289
wood_hoe: 290
stone_hoe: 291
iron_hoe: 292
diamond_hoe: 293
gold_hoe: 294
seeds: 295
wheat: 296
bread: 297
leather_helmet: 298
leather_chestplate: 299
leather_pants: 300
leather_boots: 301
chainmail_helmet: 302
chainmail_chestplate: 303
chainmail_pants: 304
chainmail_boots: 305
iron_helmet: 306
iron_chestplate: 307
